dist: xenial
services:
- postgresql
addons:
  postgresql: '9.4'
before_script:
- psql -U postgres -c "create user decide password 'decide'"
- psql -U postgres -c "create database test_decide owner decide"
- psql -U postgres -c "ALTER USER decide CREATEDB"
language: python
python:
- '3.6'
install:
- pip install -r requirements.txt
script:
- cd decide
- cp travis_local_settings.py local_settings.py
- python ./manage.py test --keepdb
deploy:
  provider: heroku
  app: intense-coast-19714
  strategy: git
  api_key:
    secure: D/8aoVRlee/IotyHNiFLsHy0nYJbC26UXfFAO4hbLokFGlVoJE5ljWgBEGXpK2qqTJiSocd+KCIdsHf8zIYoVeaMgTkxBa9Uazp/hNVkWQIASNNdSoBTBK64ktQJIBWOPaajZMWOgBWgopRz/kxHDY/4vzx73dD5CfN+O/GEtJyC1ajb662E8a11k8XvoB5KoUeQ6x/OgSiqF0yXgwYpN4FHxya0mKPQ41Eeg4/Z22X9+wwL8xTBTx7PWsA7GSJ3ECCItjJplk/cTY9W/4wiSo/r1BQggO0YxgeOiR/cjqC4ifJhOL36yD1sbl29FsGrpASCYtSrWvIK4rDuE/HlfCFtRK8TWMns7pa/GmlyjKfkISYDSwtWhqg6elRLq4nACRpb5RjZtfonJZ57I7nV8awLyTJvsuKKbzhZU+xia3l1FA597njVFXjWU3Kp3KQrp6Ta0v5opvdyx27B2fuZZ0TlyhEcPpL8PN/lZGByCrhuPaCFkYobQ0QUy49Y/BIijxA0cYBzFI95/FU1NTkx5WQVXAR/ehESX4lISZRk1BGIweNoet1ec9jgFLRQrqWYL+Fr0AaozwMo+sdZON8txHgoPeP+cvO8Zy/Gc3LckLBzWhChckoHd36EN6TLIzQB9VR3F/mzbVwDhXZ59qJ2MehmqRKKI84hIaYYCe48oUU=
